### ISSUE TITLE
开发计划

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/update-aquatic#1]
## 说明

这是一个一次性使用的插件，服务器启动后执行更新命令，即异步扫描所有( x, z )坐标执行相应的操作，直到结束。

异步生成同一个种子的世界，每个方块坐标如果是水域 biome 则新旧世界比较，如果一个在水平面以下、海床以上的方块满足：

1. 新世界里是水草、海带、海晶石、珊瑚、海泡菜、海晶灯... 等等方块
2. 旧世界里是水，没有其他任何东西
3. 周围 3x3 区域内没有水下自然方块之外的方块
4. 如果是水草、海带则必须下面有方块

即将新世界的这些水下方块复制到旧世界里

以及

旧世界和新世界都是水域的群系
将旧世界的水域群系改为新世界的

**Comment by NyanMeow** [comment]
提问 EpicWorld生成器的地形呢？

**Comment by phoenixlzx** [comment]
目前发现问题：

- [x] 河流群系更新不正常
- [x] 海岛、一部分沿岸更新不正常
- [x] 由于只更新 64 以下的方块，冻洋会不正常。可能需要特殊处理
- [x] ~~玩家渔场（和类似结构）会被渗入新的方块，但是基本不影响使用~~
- [x] 宝箱被复制后似乎丢失了 NBT 标签，不再是宝箱了（spectator 模式玩家可以打开箱子）
- [x] chunk 操作参数过大（100）可能会导致 chunk 无法被加载，玩家会因 timeout 被踢。重启服务器无法解决问题。

需要修改的：

- [x] 提供 chunk 更新模式
- [x] 提供全图更新模式
