### ISSUE TITLE
更新海域的速度较慢

### ISSUE THREAD

**Issue by timeance** [NyaaCat/update-aquatic#2]
更新速度有点慢，主要是：
- 速率设置为每`1tick`更新一个区块，那上亿个区块真的要数月的时间 = =
- 在实际使用的过程中会走走停停，不是一直连续的在执行
- 有时候会更新较少的区块
  - 暂停并移除当前任务后再重新执行`updaq chunk`会发现需要更新的区块数很少，只有一百多个区块
  - 等待那一百多个区块全部更新完成后再重新执行更新，都只有1个区块需要更新

>服务端版本:git-Paper-633 (MC: 1.13.2)

**Comment by phoenixlzx** [comment]
- 你可以用相同的种子预生成这个地图，更新区块速度可以快很多。喵窝的地图半径 15360 用了大半个月。
- 走走停停可能是你要更新的旧世界里有未生成的区块，这部分是跳过的。可以优化，要等开发者有时间。
- 暂停目前似乎有问题，所以不推荐使用。

**Comment by timeance** [comment]
感谢回复！

刚才我将旧地图再次填充生成完毕并将临时地图预生成后，速度显著提升，在更新非海洋群系的时候每个区块耗时大约是原先的 1/3 

~~要命了，机器差地图还不算小~~

**Comment by phoenixlzx** [comment]
( ´∀`)σ)Д`)
